### PR TITLE
v0.0.22

### PR DESCRIPTION
**Pull request by Bl4Cc4t**
## Features
- trends fixed
- 404 page styling
- options to hide trends and “who to follow”
- settings and messages pages styled
- Traditional Chinese translation added (Thanks [@roy4801](https://github.com/roy4801))
- added option to hide the recently added message box ([#124](https://github.com/Bl4Cc4t/GoodTwitter2/issues/124))

### CODE REVIEW

**Comment by Bl4Cc4t** [comment]
@Lastorder-DC @krokerik @Aridow @Gizel-jiz @BrandtnerKPW @granmacco 
(I hope it’s okay to ping you all everytime, I feel kinda bad doing this)

I added some more strings that need a translation.
The ones in question are
https://github.com/Bl4Cc4t/GoodTwitter2/blob/b9f8549d47b92162ad1e8fef839617bb2d7382c5/i18n/en.json#L35-L36

I also added the strings for the translate tweet button for all languages:
https://github.com/Bl4Cc4t/GoodTwitter2/blob/b9f8549d47b92162ad1e8fef839617bb2d7382c5/i18n/en.json#L11-L12
you can check if they’re correct if you want to.

**Comment by granmacco** [comment]
Added and pull requested.

I was wondering... maybe you could streamline the process of internationalization adding the english strings to every available language, but an starting asterisk or something like that. That way, we can just load the file, search for them and translate :)

**Comment by Bl4Cc4t** [comment]
@granmacco Hm, good idea! I’ll add that!

**Comment by Bl4Cc4t** [comment]
In a63a0cc96aae85bd5b758c61ce40c369d8961b67, I noticed that there is a way to get some of the default strings used on the site, so removed a bunch of custom translated ones. So don’t be surprised when you see the file being shorter

**Pull request merged**
