### PR TITLE
v0.0.21

### PR DESCRIPTION
**Pull request by Bl4Cc4t**
## Features
- French translation added (Thanks [@Aridow](https://github.com/Aridow)!)
- Korean translation added (Thanks [@Lastorder-DC](https://github.com/Lastorder-DC)!)
- Violentmonkey support (be gone, CSP issues!) thanks to [@tophf](https://github.com/tophf) (see [#96](https://github.com/Bl4Cc4t/GoodTwitter2/issues/96#issuecomment-643209498))
- various cosmetic fixes
- added changelog
- added translation button for tweets in timeline ([#32](https://github.com/Bl4Cc4t/GoodTwitter2/issues/32))

### CODE REVIEW

**Comment by Bl4Cc4t** [comment]
@krokerik @granmacco 
I hope it is okay to ping you here :)
Since v0.0.20, I added 4 additional strings to localize the settings, would you be so kind and update your translations please?
https://github.com/Bl4Cc4t/GoodTwitter2/blob/0a4904c09da789dbdf4528c6a490c3ef059e3454/i18n/en.json#L12-L14
https://github.com/Bl4Cc4t/GoodTwitter2/blob/0a4904c09da789dbdf4528c6a490c3ef059e3454/i18n/en.json#L25

**Comment by granmacco** [comment]
No problem. Also, although lots of  the spanish users use the term "timeline" too, I guess using "cronología", the term used in the official Twitter web, is more appropiate.

You have it ready for merging in the pull requests :)

**Comment by arturo182** [comment]
Version not bumped 😂

**Comment by Bl4Cc4t** [comment]
Thanks for reminding me :D

**Pull request merged**
