### PR TITLE
Add Polish translation

### PR DESCRIPTION
**Pull request by mkljczk**
Should work fine after enabling it.

### CODE REVIEW

**Review by Bl4Cc4t — CHANGES_REQUESTED** [review]
Nice, thanks for your contribution!
Some day, all languages are supported :D

There is an upcoming change though, could you please include the highlighted line here as well?
https://github.com/Bl4Cc4t/GoodTwitter2/pull/246/files#diff-1a490f08504158838befaa816ee8d5c08dff9e694d5a568ce4b0a4398dcc563eR51

**Comment by mkljczk** [comment]
done @Bl4Cc4t

**Comment by Bl4Cc4t** [comment]
Perfect, thanks again!

**Comment by Bl4Cc4t** [comment]
Arrrgh, I merged into master. Oh well.

**Pull request merged**
