### PR TITLE
Update ru.json

### PR DESCRIPTION
**Pull request by BrandtnerKPW**
"settingsHeaderGlobalLook" and "tweetIconsPullLeft"

I'm not sure if I understood the meaning of the "tweetIconsPullLeft" function correctly. What changes when it is applied?

### CODE REVIEW

**Comment by Bl4Cc4t** [comment]
> I'm not sure if I understood the meaning of the "tweetIconsPullLeft" function correctly. What changes when it is applied?

This setting changes the alignment of the comment, retweet, like and share buttons under tweets.
It was requested here: #278 

I agree that the wording might not be very good. Do you perhaps have a better idea?

**Comment by BrandtnerKPW** [comment]
Maybe something like "Shrink Tweet Interaction Buttons to the Left"?

**Comment by Bl4Cc4t** [comment]
I changed the wording to "Bunch up Tweet Interaction Buttons to the Left" now, but I'm sure your translation works just fine!
I'll wait with the merge in case you want to change something though.

**Comment by BrandtnerKPW** [comment]
Yes, I think you can merge it. No changes required.

**Pull request merged**
