### PR TITLE
v0.0.20

### PR DESCRIPTION
**Pull request by Bl4Cc4t**
## Feature List
- Japanese and Russian translation added! (Thanks @Gizel-jiz & @BrandtnerKPW)
- better color theme detection (no need to adjust anything anymore when installing for the first time)
- fixed many display issues
- properly scrollable sidebars
- option to always show 10 trends
- site is now usable without being logged in
  - additional feature: you can toggle nightmode by clicking on the little moon in your dashboard profile :)
- added notice to enable CSP on Firefox again!

For v0.0.21, I will focus on the timeline I think (new tweet detection)

(so many commits here because I used a squash merge for v0.0.19...)

### CODE REVIEW

**Comment by arturo182** [comment]
Remember version number :D

**Comment by Bl4Cc4t** [comment]
did that ealier this time :D

**Comment by arturo182** [comment]
Oh? It's still showing 18 in the diff:

image

**Comment by Bl4Cc4t** [comment]
now I’m tripping, I could swear I already changed it

**Comment by arturo182** [comment]
I installed this version cause I'm an impatient bastard and there are two undefined items settings:
image

**Comment by Bl4Cc4t** [comment]
you need to manually adjust `twitter.gt2eb.style.css` and `twitter.gt2eb.i18n.js` from the externals tab :)

**Comment by arturo182** [comment]
Damn, you're right, sorry for wasting your time, I'll just go back to master.

**Comment by Bl4Cc4t** [comment]
You are free to test the dev branch if you want to, just change replace every occurence of `master` with `dev`, that also works.

**Pull request merged**
