### PR TITLE
Japanese Translation @Gizel-jiz

### PR DESCRIPTION
**Pull request by Gizel-jiz**
I Created a translation file for Japanese.
Note:I'm sorry if I made a mistake because this is the first time for me.

### CODE REVIEW

**Comment by Bl4Cc4t** [comment]
Thank you for that!
First time translating or first time using git? :)

**Comment by Gizel-jiz** [comment]
Thanks for the reply!

This is my first time working with git for development and tool translation. :)
The translation itself was finished quickly, with reference to other people's languages as well.
However, since it was my first time, it took me a while to get a pull request, etc. :(
I'm sorry if there are any mistakes.

**Comment by Bl4Cc4t** [comment]
Hm, I fixed some things, please accept the changes :)

**Comment by Gizel-jiz** [comment]
I apologize for the inconvenience caused by our mistake.
Should I just keep waiting for it to be fixed and good twitter2 to be updated?

**Comment by Bl4Cc4t** [comment]
I fixed them, but you have to accept them

**Comment by Bl4Cc4t** [comment]
Oh I’m sorry, I forgot to actually send it.
I do not use this feature very often :/

**Comment by Bl4Cc4t** [comment]
Thank you and sorry again that I confused you earlier ^^’

**Comment by Gizel-jiz** [comment]
Don't worry about it.
I've just given my consent to the amendment, is that correct?

**Comment by Bl4Cc4t** [comment]
yes, the changes were applied

**Pull request merged**
