### PR TITLE
enable redirect from mobile.twitter.com

### PR DESCRIPTION
**Pull request by geyerbri**
Added code to automatically redirect mobile.twitter.com urls to twitter.com. 

Addresses #104.

### CODE REVIEW

**Comment by geyerbri** [comment]
I should add, I only tested this in Opera Version 87, via Tampermonkey, on Windows 10.

**Comment by Bl4Cc4t** [comment]
Thanks for this, I'll look into this tomorrow or so and add a toggle!

**Comment by geyerbri** [comment]
To make this easier, I went ahead and figured out how the Settings menu works, then added the option (turned off by default) to toggle the mobile redirect. I added it to each translation .yml too, using the #todo note about not having been translated yet for all of them (except in en.yml obviously).

**Comment by Bl4Cc4t** [comment]
Oh I'm sorry for always abandoning this project and its issues all the time :/

> I added it to each translation .yml too, using the #todo note about not having been translated yet for all of them (except in en.yml obviously).

There is a script here that does that automatically: [util/add-new-strings-i18n.js](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/util/add-new-strings-i18n.js)

---
Looking at the code, you moved the url checks more to the bottom...
Checking the url for redirection purposes should be at the top of the script, so that there is as little delay as possible.

**Comment by geyerbri** [comment]
Sure thing! 

I moved it down because I thought it was beneficial to fit it into the structure you had for other toggled options, not thinking about the speed. I can easily move it all back up to the top (I think I tested a version with it all at the top and the toggle still worked, but I'll re-test). Give me a few hours and I'll have the move done.

**Comment by Bl4Cc4t** [comment]
mentioning the tool was just to point out that you needn't to go through the trouble of adding the translations yourself
you even edited i18n.js? Oh noes, that gets generated automatically as well with every new version, it's not meant to be edited by hand, that's way to tedious...

You just did more than what you needed, you can just leave it like that

Also, I'd prefer if you could try out the suggestion from above I made, it's just one if block for everything

**Comment by geyerbri** [comment]
Ok hopefully this is in line with what you're thinking. I tried to pare it down to as simple as I am able to make it with my skills. If you also mean that there's a way to get the new Settings entry and default value into the same `if` block, I'm not sure how to go about doing it.

As before, tested on Windows 10, Opera 87, Tampermonkey 4.16.

**Comment by Bl4Cc4t** [comment]
Okay great, I'll merge this then. Thanks again!

**Pull request merged**
