### PR TITLE
v0.0.44

### PR DESCRIPTION
**Pull request by Bl4Cc4t**
#### New
- replaced doge logo (???) with twitter logo

#### Changes
- fixed username showing up twice in the small profile view
- translations updated

### CODE REVIEW

**Comment by Quesito35** [comment]
Hello.
I am writing to you from Spain.
I have GoodTwitter2 v0.0.44 installed on a desktop computer.
Installed Violentmonkey Version 2.14.0
I use Windows 11Pro 22H2.
I have Google Chrome, Microsoft Edge Chromium and Brave browsers.
Yesterday, 04/3/2023, everything was working correctly on the twitter.com website.
Today 4/4/2023 the script no longer works, Twitter shows as if it had no script installed. (screenshot attached)
I have tried in all three browsers and none of them work.
Waiting for help.

GoodTwitter2 v-0044

**Comment by Quesito35** [comment]
Hello again.
The bug seems to be in GoodTwitter2 v.0.0.44.
I have been in contact with a friend of mine and her in v.0.0.43.2 the script works correctly. (Attachment screenshot).
The question is: If I have GoodTwitter2 v.0.0.44, how can I go back and install version 0.0.43.2 in Google Chrome, Microsoft Edge Chromium and Brave browsers?
If I go to the link https://github.com/Bl4Cc4t/GoodTwitter2 "Installation" I always get version 0.0.44.
Waiting for some help.
Thank you.
Inked13_LI

**Comment by Bl4Cc4t** [comment]
please don't comment issues on pull requests :/
you could've opened #539 in the first place :)

**Comment by Quesito35** [comment]
Sorry.

**Pull request merged**
